### ISSUE TITLE
[BUG] Practically no ahk script is compatible. For example:

### ISSUE THREAD

**Issue by BlackRule** [Nordgedanken/auto_hot_key_jetbrains_plugin#29]
IDEA 2020.1.4
Error indexing:file://C:/Users/Rules/Desktop/AHK/123.ahk

java.lang.IllegalStateException: @NotNull method com/intellij/psi/stubs/StubIndexImpl.getKeyHashingStrategy must not return null
	at com.intellij.psi.stubs.StubIndexImpl.$$$reportNull$$$0(StubIndexImpl.java)
	at com.intellij.psi.stubs.StubIndexImpl.getKeyHashingStrategy(StubIndexImpl.java:267)
	at com.intellij.psi.stubs.SerializedStubTree.lambda$indexTree$0(SerializedStubTree.java:199)
	at com.intellij.psi.stubs.ObjectStubTree$StubIndexSink.occurrence(ObjectStubTree.java:140)
	at de.nordgedanken.auto_hotkey.stubs.StubIndexingKt.indexNamedStub(StubIndexing.kt:12)
	at de.nordgedanken.auto_hotkey.stubs.StubIndexingKt.indexFunction(StubIndexing.kt:7)
	at de.nordgedanken.auto_hotkey.stubs.AHKFunctionStub$Type.indexStub(AHKFunctionStub.kt:33)
	at de.nordgedanken.auto_hotkey.stubs.AHKFunctionStub$Type.indexStub(AHKFunctionStub.kt:12)
	at com.intellij.psi.stubs.ObjectStubTree.indexStubTree(ObjectStubTree.java:78)
	at com.intellij.psi.stubs.SerializedStubTree.indexTree(SerializedStubTree.java:199)
	at com.intellij.psi.stubs.SerializedStubTree.serializeStub(SerializedStubTree.java:70)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.lambda$computeValue$0(StubUpdatingIndex.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:894)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.computeValue(StubUpdatingIndex.java:126)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.computeValue(StubUpdatingIndex.java:99)
	at com.intellij.util.indexing.SingleEntryCompositeIndexer.computeValue(SingleEntryCompositeIndexer.java:27)
	at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:28)
	at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:17)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:317)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:309)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:150)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:40)
	at com.intellij.util.indexing.impl.MapReduceIndex.calculateUpdateData(MapReduceIndex.java:267)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:239)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1253)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$20(FileBasedIndexImpl.java:1181)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:723)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1161)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1147)
	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$indexFiles$2(UnindexedFilesUpdater.java:130)
	at com.intellij.openapi.project.CacheUpdateRunner.lambda$null$1(CacheUpdateRunner.java:208)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.project.CacheUpdateRunner.lambda$null$2(CacheUpdateRunner.java:224)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.project.CacheUpdateRunner.lambda$createRunnable$3(CacheUpdateRunner.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:198)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
file:
$Launch_App2:: ;not trigger itself; On Calculator
SetKeyDelay, 500,250 ;Delay, PressDuration
;
Send ^c ;ctrl
Send {Right,2} ;switch to name cell
Send ^c  ;
Send {Right} ;switch to address cell
Send ^c  ;
Send ^t ; Open a new tab, and jump to it
Send ^l ;Choose addressbar
Send #v ;win+v
Send {Down,2}
SetKeyDelay, 300,64
Send {Enter}
Send {Space}
Send #v ;win+v
Send {Down} 
Send {Enter} ;paste 
Send {Space}
Send #v
Send {Enter}
Send {Enter}
return
How it's rendered:
https://prnt.sc/tngyib

**Comment by MTRNord** [comment]
Hi this is known. I actually plan to rewrite the language parsing. It is a) not finisched yet and b) the code got really messy really fast. Therefor I plan to rewrite the language parsing now :)
